apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    cert-manager.io/cluster-issuer: technitium-letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - is-controlplane-0.group-4.doe24.chas-lab.dev
    secretName: argocd-tls
  rules:
  - host: is-controlplane-0.group-4.doe24.chas-lab.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: https
