apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: traefik
spec:
  secretName: wildcard-tls
  issuerRef:
    name: technitium-letsencrypt-staging
    kind: ClusterIssuer
  commonName: "control-plane-1.group-4.doe24.chas-lab.dev"
  dnsNames:
    - "control-plane-1.group-4.doe24.chas-lab.dev"
