apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: nginx
spec:
  secretName: wildcard-tls
  issuerRef:
    name: technitium-letsencrypt-staging
    kind: ClusterIssuer
  commonName: "is-controlplane-0.group-4.doe24.chas-lab.dev"
  dnsNames:
    - "is-controlplane-0.group-4.doe24.chas-lab.dev"
    - "is-controlplane-0.group-4.doe24.chas-lab.dev"
