# Cert-manager application manifest
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    # NOTE: Update to the latest stable if desired.
    targetRevision: "v1.14.4"
    helm:
      values: |
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  spec:
    containers:
    # Wait job to ensure cert-manager is fully synced before proceeding
      - name: wait for cert-manager sync to complete
        image: alpine:latest
        command: ["/bin/sh", "-c", "sleep 20"]
        
