apiVersion: batch/v1
kind: Job
metadata:
  name: install-cert-manager-pre
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: install-crds-and-ns
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Create namespace for cert-manager if it doesn't exist
          kubectl get ns cert-manager || kubectl create ns cert-manager
          
          # Install CRDs
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.crds.yaml
