apiVersion: batch/v1
kind: Job
metadata:
  name: install-cert-manager-crds
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: install-crds
        image: bitnami/kubectl
        command: ["kubectl", "apply", "-f", "https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.crds.yaml"]
      restartPolicy: OnFailure