# Deploys ClusterIssuer manifest (thats in /cluster-issuer directory)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt-cluster-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://gitlab.com/devopsgp4/argocd.git
    targetRevision: HEAD
    path: cluster-issuer
    directory:
      recurse: true
  # Deploys the manifest in cert-manager namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: {}