apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/depends-on: cert-manager
spec:
  secretName: wildcard-cert
  issuerRef:
    name: letsencrypt
    # Clusterwide issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.exam.doe24.chas-lab.dev"
    - "exam.doe24.chas-lab.dev" 