apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: argocd
  argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: wildcard-cert
  issuerRef:
    name: letsencrypt
    # Clusterwide issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.group-4.doe24.chas-lab.dev"
    - "group-4.doe24.chas-lab.dev" 