apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbac:secret-reader
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["technitium-api-token"]
    verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac:secret-reader
subjects:
  - kind: ServiceAccount
    name: cert-manager-webhook-technitium-cert-manager-technitium-webhook
    namespace: cert-manager