apiVersion: v1
kind: Secret
metadata:
  name: technitium-api-token
  namespace: cert-manager
type: Opaque
stringData:
  # Replace this with your actual API token string
  api-token: "7df9afa459e1a0c87de49acaeafe8930d8e612e4ff6b72e679f512bf35daa630"