apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rfc2136-credentials
  namespace: kube-system
spec:
  encryptedData:
    tsig_secret_key: AgBn7PKeo4OeTxtJNV72M4hhwXSltNWIJTTAGfmteQ+L/YNGtOL2EEmKtPzZ4Xh/cOBWwRjA+EVoYi/sjW+ImhNRAtoNY/LXhrsoYU/dikcrOZ23v5pfq4Kh7DEMS00jNvjyVSXatpfZgwLayYdJNW6TMt7ycBkQDN8IYSxd1uzbobjE4t/pjknuDBZFJUSYzp+4ikX/3v/CeXEw5hdCdW3Ze3lIT6xXfDNmvelF/aJ+pMIjoK9/FOg0p5wRcNPggEJuAeaQyT0Vk8J5N2RjL4zndb+oXpygGNgC8yz1u5/qV+a97OLhEQjUknSkJv2cN3I45SDkBjQAxDKNIzeFAwfDweWvryzdVhYiT4tsp4/DLx0EePCgpG6gx+wUaGrcs65qVPGwfWZX9ftSRdQaonSJJdft5X7lj7li1ylKBNTlAdVsV9zzDfJg4HSx3iUKAIYhVM0NaRyD3NfmVBTovVyrQiNgJwcCI5pogk7O2IlIZFwm7AgIWfjIWyA+tWfep5GsXEzVOC45ApsKaZ+lcDxi+vh1hXfbEL42X9JuHuCsIa5B/fPNjd96+6FQMtCoN+tiYq1AXfIGB2YOCLvY/FiR8m7jtupIPnI7myBQWl6t+fKe8IS1rozwwPpUYb9iAtUADAe990prjSAw8E4mG8UBdmEg5Bg10jMsOVEFmFR1kQArHqZ96DQHQ7V0yJTTlbNlsl4aFtCviSHL1jXxgHvrv+T+ZSSXIUoq5qW9TiOAAHPMmK9xZrnvWrWtpw==
  template:
    metadata:
      name: rfc2136-credentials
      namespace: kube-system
